image: Visual Studio 2017
platform:
  - x86
  - x64
configuration:
  - Debug
  - Release
artifacts:
if [$(platform)] == "x86"(
  - path: $(configuration)\*.*
    name: RequestsLib$(configuration)$(platform)
)else(
  - path: x64\$(configuration)\*.*
    name: RequestsLib$(configuration)$(platform)
    )
