image: Visual Studio 2017
platform:
  - x86
  - x64
configuration:
  - Debug
  - Release
    
artifacts:
  - path: if "%Platform%" == "x86" ($(configuration)\*.*) else ( x64\$(configuration)\*.* )
    name: RequestsLib$(configuration)$(platform)
